#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff check"
entry = "uv run ruff check"
language = "system"
types_or = ["python", "pyi"]
require_serial = true
priority = 0

[[repos.hooks]]
id = "ruff-format"
name = "ruff format (check)"
entry = "uv run ruff format --check"
language = "system"
types_or = ["python", "pyi"]
require_serial = true
priority = 0

[[repos.hooks]]
id = "basedpyright"
name = "basedpyright"
entry = "uv run basedpyright"
language = "system"
types_or = ["python", "pyi"]
pass_filenames = false
require_serial = true
priority = 0

[[repos]]
repo = "https://github.com/DavidAnson/markdownlint-cli2"
rev = "v0.22.1"
hooks = [{ id = "markdownlint-cli2", priority = 0 }]
